// Spoken Polish for the monotonicity theory episode. Every scene is written as
// a continuous explanation, with numerals spelled out for the voiceover.
export const monotonicityNarration: Record<string, string> = {
  "theory-00-hook": "Cześć! Mam dla ciebie małą zagadkę. Co jest większe: siedem do minus trzeciej czy siedem do minus drugiej? A jeśli zamiast siódemki wstawimy ułamek, czy odpowiedź pójdzie w tę samą stronę? Dziś pokażę ci prostą zasadę, która rozstrzyga oba pytania bez liczenia wielkich potęg. Zaczniemy od intuicji, przejdziemy przez przykłady i na koniec użyjemy jej w zadaniu podobnym do maturalnego. Wystarczy, że za każdym razem spojrzysz najpierw na podstawę.",
  "theory-concept-1": "Zanim porównamy potęgi, ustawmy granice tej reguły. Podstawa ma być dodatnia, bo wtedy potęga jest określona dla każdego rzeczywistego wykładnika i jej wartość pozostaje dodatnia. Nawet ujemny wykładnik nie robi z wyniku liczby ujemnej. Na przykład dwa do minus trzeciej to jedna ósma. To często zaskakuje, więc zatrzymaj się przy tej myśli: minus w wykładniku oznacza odwrotność, a nie zmianę znaku. Za chwilę wykorzystamy to przy porównywaniu z jedynką.",
  "theory-concept-2": "Sedno lekcji mieści się w jednym pytaniu: czy podstawa leży powyżej jedynki, czy pomiędzy zerem a jedynką? Kiedy jest większa od jedynki, większy wykładnik daje większy wynik. Kiedy jest dodatnim ułamkiem mniejszym od jedynki, większy wykładnik daje mniejszy wynik. Wyobraź sobie, że mnożysz przez dwa: liczba rośnie. Gdy mnożysz przez jedną drugą, maleje. Ta intuicja dotyczy też wykładników ujemnych i ułamkowych, chociaż wtedy nie myślimy dosłownie o kolejnych mnożeniach.",
  "theory-concept-3": "Weźmy podstawę większą od jedynki, na przykład dwójkę. Dwa do zera daje jeden, dwa do pierwszej daje dwa, a dwa do drugiej daje cztery. Wykładniki rosną i wartości rosną razem z nimi. Tak samo jest, gdy wykładnik jest ujemny: dwa do minus trzeciej jest mniejsze od dwa do minus drugiej, bo minus trzy leży na osi na lewo od minus dwóch. Nie trzeba liczyć obu ułamków. Najpierw rozpoznajesz podstawę, potem porównujesz wykładniki.",
  "theory-concept-4": "Teraz odwróćmy sytuację i wybierzmy podstawę jedną drugą. Jej kolejne dodatnie potęgi to jedna druga, jedna czwarta i jedna ósma. Wykładnik idzie w górę, ale wartości idą w dół. Dlatego przy podstawie pomiędzy zerem a jedynką znak nierówności między wykładnikami odwraca się dla potęg. To najczęstsza pułapka w tym temacie. Nie zapamiętuj samego ruchu ze znakiem. Pomyśl o ułamku, który przy kolejnym mnożeniu staje się mniejszy.",
  "theory-method-1": "Jak używać tej zasady w zadaniu? Najpierw sprawdź, czy obie potęgi mają tę samą podstawę. Jeśli tak, umieść ją po właściwej stronie jedynki. Dopiero potem porównaj wykładniki i zdecyduj o kierunku znaku. Jeżeli podstawy są różne, spróbuj zapisać je jako potęgi jednej liczby. To działa choćby dla dziewiątki i dwudziestu siedmiu, bo obie są potęgami trójki. Nie porównuj samych wykładników, dopóki podstawy nie są takie same.",
  "theory-method-2": "Druga przydatna sytuacja to porównanie potęgi z jedynką. Jedynkę możesz zawsze zapisać jako dodatnią podstawę do potęgi zerowej. Wtedy patrzysz tylko, czy twój wykładnik jest dodatni, zerowy czy ujemny oraz po której stronie jedynki leży podstawa. Dla liczby większej od jedynki dodatni wykładnik daje wynik większy od jedynki. Dla ułamka mniejszego od jedynki dzieje się odwrotnie. Ta mała sztuczka oszczędza liczenia i szybko ujawnia błędy ze znakiem.",
  "theory-formula-1": "Zapiszmy tę regułę językiem nierówności. Gdy pierwsza wartość wykładnika jest mniejsza od drugiej, a podstawa większa od jedynki, pierwsza potęga też jest mniejsza. To właśnie znaczy, że potęgowanie jest rosnące względem wykładnika. Możesz sprawdzić to na dwójce albo piątce, ale wzór działa dla każdej stałej podstawy większej od jedynki. Warunek o tej samej podstawie jest tu kluczowy. Bez niego taki skrót myślowy może prowadzić do złej odpowiedzi.",
  "theory-formula-2": "A teraz druga wersja wzoru. Jeśli dodatnia podstawa jest mniejsza od jedynki, mniejszy wykładnik daje większą potęgę. Mówimy wtedy, że potęgowanie jest malejące. Zauważ także przypadek graniczny: jeden do dowolnej potęgi daje jeden. Nie dostaniemy więc ani rośnięcia, ani malenia, i z równości takich potęg nie odczytamy wykładnika. Dlatego w regule o kierunku zawsze wykluczamy podstawę równą jeden. Ujemne podstawy również nie należą do tej ogólnej reguły.",
  "example-g-th-00": "Sprawdźmy to na dwóch parach. Najpierw siedem do minus trzeciej i siedem do minus drugiej. Siedem jest większe od jedynki, a minus trzy jest mniejsze od minus dwóch, więc pierwsza potęga jest mniejsza. Teraz dwie piąte do czwartej i dwie piąte do siódmej. Podstawa leży pomiędzy zerem a jedynką, więc kierunek odwracamy. Cztery jest mniejsze od siedmiu, ale pierwsza potęga jest większa. To ten sam schemat, tylko inny rodzaj podstawy.",
  "example-g-th-01": "W następnym przykładzie pytamy, które potęgi są większe od jedynki. Trzy czwarte do minus szóstej? Tak, bo ujemny wykładnik odwraca ułamek i dostajemy podstawę większą od jedynki. Dziewięć dziesiątych do piątej? Nie, kolejne mnożenie przez ułamek zmniejsza wynik. Dwa do minus trzech dziesiątych? Też nie. Podstawa dwa jest większa od jedynki, ale wykładnik leży poniżej zera, więc wynik jest poniżej dwa do zera, czyli poniżej jedynki. Bez kalkulatora mamy wszystkie odpowiedzi.",
  "example-g-th-02": "Przejdźmy do prostej nierówności. Pięć do potęgi iks minus dwa ma być mniejsze od pięć do szóstej. Obie strony mają tę samą podstawę, a pięć jest większe od jedynki. Możemy więc porównać same wykładniki bez zmiany znaku. Iks minus dwa jest mniejsze od sześciu. Dodajemy dwa po obu stronach i wychodzi iks mniejsze od ośmiu. Zbiór rozwiązań to wszystkie liczby na lewo od ośmiu, bez samej ósemki. Właśnie tu monotoniczność oszczędza nam liczenia potęg.",
  "matura-setup": "Na koniec zadanie w stylu maturalnym. Która liczba jest większa: dwadzieścia siedem do dziesiątej czy dziewięć do szesnastej? Nie obliczaj żadnej z nich w całości. Obie podstawy da się zapisać jako potęgi trójki: dwadzieścia siedem to trzy do trzeciej, a dziewięć to trzy do drugiej. To jest moment, w którym pozornie różne podstawy stają się jedną wspólną podstawą. Zatrzymaj film na chwilę i spróbuj sam wyznaczyć wykładniki po przepisaniu obu liczb. Potem sprawdzimy wynik razem.",
  "matura-calculate": "Zróbmy rachunek spokojnie. Dwadzieścia siedem do dziesiątej to trzy do trzeciej, podniesione do dziesiątej. W potędze potęgi mnożymy wykładniki, więc dostajemy trzy do trzydziestej. Dziewięć do szesnastej to trzy do drugiej, podniesione do szesnastej, czyli trzy do trzydziestej drugiej. Teraz obie strony naprawdę mają tę samą podstawę. Trzy jest większe od jedynki, więc większy wykładnik oznacza większą wartość. Trzydzieści jest mniejsze od trzydziestu dwóch, zatem wygrywa druga liczba.",
  "matura-check": "Odpowiedź brzmi: dziewięć do szesnastej jest większe niż dwadzieścia siedem do dziesiątej. Sprawdźmy, dlaczego ten wniosek jest bezpieczny. Najpierw poprawnie przepisaliśmy obie podstawy na potęgi trójki. Potem pomnożyliśmy wykładniki, bo podnosiliśmy potęgę do kolejnej potęgi. Na końcu porównaliśmy wykładniki przy tej samej podstawie większej od jedynki. Gdyby wspólna podstawa była ułamkiem mniejszym od jedynki, ostatni znak trzeba by odwrócić. Warto wypisać te trzy kroki także na maturze, żeby rozwiązanie było czytelne.",
  "theory-summary": "Zbierzmy wszystko w jedną krótką instrukcję. Upewnij się, że podstawy są takie same i dodatnie. Jeśli podstawa jest większa od jedynki, kierunek porównania wykładników zostaje. Jeśli leży pomiędzy zerem a jedynką, kierunek się odwraca. Gdy porównujesz z jedynką, zapisz ją jako potęgę o wykładniku zerowym. I pamiętaj, że podstawa równa jeden nie daje nam informacji o wykładniku. Jeśli ten film ci pomógł i lubisz takie wyjaśnienia, zasubskrybuj kanał. Napisz też w komentarzu, jaki temat chcesz zobaczyć następny. To naprawdę pomoże mi rozwijać kanał. Dzięki i do zobaczenia!"
};
